
JFLAGS = -g
JC = javac
.SUFFIXES: .java .class
.java.class:
        $(JC) $(JFLAGS) $*.java

CLASSES = \
        Lex.java \
        List.java \
        ListClient.java

default: classes

classes: $(CLASSES:.java=.class)

clean:
        $(RM) *.class